model_name: nvidia/nemotron-3.5-asr-streaming-0.6b

lora:
  rank: 8
  alpha: 16

train_ds:
  manifest_filepath: manifests/train.json

  batch_duration: 40
  max_duration: 20

  use_bucketing: true
  num_buckets: 30

  bucket_buffer_size: 10000
  shuffle_buffer_size: 10000

  num_workers: 12

validation_ds:
  manifest_filepath: manifests/val.json
  batch_size: 1
  num_workers: 4

optim:
  lr: 0.00005

trainer:
  precision: bf16-mixed
  max_epochs: 5
  accumulate_grad_batches: 8
  gradient_clip_val: 1.0
